name: SayHello

on:
 push:
   branches:
     - develop
      - main 
    
jobs:
  welcome:
     runs-on: ubuntu-latest
     
     steps:
       - name: Download your code  ğŸ™Œ
         uses: actions/checkout@v2

       - name: Say something ğŸ
         run: echo "hello world"


 hello-main: 
    runs-on: ubuntu-latest
    
     steps: 
      -name: Download your code ğŸ˜
       uses: actions/checkout@v2

       - name: Verify branch ğŸ˜Š
          if: $[[ github.ref == "refs/heads/develop"]]
          run: echo "hello develop"

          - name: Verify main develop ğŸ‰
              if: $[[ github.ref == "refs/heads/develop"]]
               run: echo "hello main"
